using System.Globalization;
using System.Security.Cryptography;

namespace ShooterMmo.Tools.SimulationStressGenerator;

public sealed record StressGeneratorOptions(
    Uri AuthorityUrl,
    string WorkerHost,
    int WorkerUdpPort,
    string WorkerId,
    string FleetId,
    string NodeId,
    string ShardId,
    string WorldId,
    string WorkerSecret,
    int BotCount,
    int BotStartIndex,
    int RampStep,
    TimeSpan RampInterval,
    TimeSpan SteadyDuration,
    TimeSpan WorkerWaitTimeout,
    TimeSpan JoinTimeout,
    TimeSpan ReportInterval,
    int Seed,
    string OutputPath)
{
    public const int MaximumBotCount = 10_000;

    public static StressGeneratorOptions Parse(string[] args, string workingDirectory)
    {
        ArgumentNullException.ThrowIfNull(args);
        ArgumentException.ThrowIfNullOrWhiteSpace(workingDirectory);

        var values = ParseValues(args);
        var authorityUrl = ParseHttpUri(
            Get(values, "authority-url", "http://127.0.0.1:5099"),
            "authority-url");
        if (!authorityUrl.IsLoopback)
        {
            throw new StressGeneratorOptionException(
                "--authority-url must use a loopback address so the stress authority is not exposed to the network.");
        }

        var workerSecret = Get(values, "worker-secret", CreateSecret());
        if (workerSecret.Length < 32)
        {
            throw new StressGeneratorOptionException(
                "--worker-secret must contain at least 32 characters.");
        }

        var botCount = ParseInt(values, "bots", 100, 1, MaximumBotCount);
        var botStartIndex = ParseInt(values, "bot-start-index", 1, 1, int.MaxValue - botCount);
        var rampStep = ParseInt(values, "ramp-step", Math.Min(25, botCount), 1, botCount);
        var output = Get(
            values,
            "output",
            Path.Combine(
                workingDirectory,
                "artifacts",
                "stress",
                $"simulation-stress-{DateTime.UtcNow:yyyyMMdd-HHmmss}.json"));

        return new StressGeneratorOptions(
            authorityUrl,
            Require(Get(values, "worker-host", "127.0.0.1"), "worker-host"),
            ParseInt(values, "worker-udp-port", 27015, 1, ushort.MaxValue),
            Require(Get(values, "worker-id", "local-simulation-worker-1"), "worker-id"),
            Require(Get(values, "fleet-id", "local-fleet"), "fleet-id"),
            Require(Get(values, "node-id", "local-node-1"), "node-id"),
            Require(Get(values, "shard-id", "local-shard-1"), "shard-id"),
            Require(Get(values, "world-id", "development-world-1"), "world-id"),
            workerSecret,
            botCount,
            botStartIndex,
            rampStep,
            TimeSpan.FromSeconds(ParseInt(values, "ramp-interval-seconds", 10, 1, 3600)),
            TimeSpan.FromSeconds(ParseInt(values, "duration-seconds", 300, 1, 86_400)),
            TimeSpan.FromSeconds(ParseInt(values, "worker-wait-seconds", 120, 1, 3600)),
            TimeSpan.FromSeconds(ParseInt(values, "join-timeout-seconds", 10, 1, 300)),
            TimeSpan.FromSeconds(ParseInt(values, "report-interval-seconds", 10, 1, 3600)),
            ParseInt(values, "seed", 1337, int.MinValue, int.MaxValue),
            Path.GetFullPath(output, workingDirectory));
    }

    public static bool IsHelpRequested(string[] args)
    {
        return args.Any(argument => argument is "--help" or "-h" or "/?");
    }

    public static string HelpText =>
        """
        SimulationStressGenerator

        Hosts an in-memory stress authority and drives headless LiteNetLib bots
        through the real SimulationWorker join and movement protocol.

        Options:
          --authority-url <url>             Loopback authority URL. Default: http://127.0.0.1:5099
          --worker-host <host>              UDP host used by bots. Default: 127.0.0.1
          --worker-udp-port <port>          UDP port used by bots. Default: 27015
          --worker-id <id>                  Expected worker id. Default: local-simulation-worker-1
          --fleet-id <id>                   Expected fleet id. Default: local-fleet
          --node-id <id>                    Expected node id. Default: local-node-1
          --shard-id <id>                   Expected shard id. Default: local-shard-1
          --world-id <id>                   World returned by the authority. Default: development-world-1
          --worker-secret <secret>          Ephemeral worker secret. A random value is generated by default.
          --bots <count>                    Total bots. Default: 100
          --bot-start-index <index>         First bot display index. Default: 1
          --ramp-step <count>               Bots added per ramp interval. Default: 25
          --ramp-interval-seconds <seconds> Delay between ramp steps. Default: 10
          --duration-seconds <seconds>      Steady-load duration after the ramp. Default: 300
          --worker-wait-seconds <seconds>   Worker registration timeout. Default: 120
          --join-timeout-seconds <seconds>  Per-bot join timeout. Default: 10
          --report-interval-seconds <sec>   Console report interval. Default: 10
          --seed <number>                   Deterministic movement seed. Default: 1337
          --output <path>                   JSON result path under artifacts/stress by default.
        """;

    private static Dictionary<string, string> ParseValues(string[] args)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var index = 0; index < args.Length; index++)
        {
            var argument = args[index];
            if (argument is "--help" or "-h" or "/?")
            {
                continue;
            }

            if (!argument.StartsWith("--", StringComparison.Ordinal)
                || argument.Length <= 2)
            {
                throw new StressGeneratorOptionException(
                    $"Unknown argument '{argument}'. Use --help to list supported options.");
            }

            var key = argument[2..];
            if (index + 1 >= args.Length
                || args[index + 1].StartsWith("--", StringComparison.Ordinal))
            {
                throw new StressGeneratorOptionException($"Option '--{key}' requires a value.");
            }

            if (!values.TryAdd(key, args[++index]))
            {
                throw new StressGeneratorOptionException($"Option '--{key}' was provided more than once.");
            }
        }

        var supported = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "authority-url",
            "worker-host",
            "worker-udp-port",
            "worker-id",
            "fleet-id",
            "node-id",
            "shard-id",
            "world-id",
            "worker-secret",
            "bots",
            "bot-start-index",
            "ramp-step",
            "ramp-interval-seconds",
            "duration-seconds",
            "worker-wait-seconds",
            "join-timeout-seconds",
            "report-interval-seconds",
            "seed",
            "output"
        };
        var unsupported = values.Keys.FirstOrDefault(key => !supported.Contains(key));
        if (unsupported is not null)
        {
            throw new StressGeneratorOptionException(
                $"Unknown option '--{unsupported}'. Use --help to list supported options.");
        }

        return values;
    }

    private static string Get(
        IReadOnlyDictionary<string, string> values,
        string key,
        string fallback)
    {
        return values.TryGetValue(key, out var value) ? value : fallback;
    }

    private static int ParseInt(
        IReadOnlyDictionary<string, string> values,
        string key,
        int fallback,
        int minimum,
        int maximum)
    {
        if (!values.TryGetValue(key, out var raw))
        {
            return fallback;
        }

        if (!int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value)
            || value < minimum
            || value > maximum)
        {
            throw new StressGeneratorOptionException(
                $"--{key} must be an integer between {minimum} and {maximum}.");
        }

        return value;
    }

    private static Uri ParseHttpUri(string value, string key)
    {
        if (!Uri.TryCreate(value, UriKind.Absolute, out var uri)
            || uri.Scheme != Uri.UriSchemeHttp)
        {
            throw new StressGeneratorOptionException(
                $"--{key} must be an absolute HTTP URL.");
        }

        return uri;
    }

    private static string Require(string value, string key)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new StressGeneratorOptionException($"--{key} cannot be empty.");
        }

        return value.Trim();
    }

    private static string CreateSecret()
    {
        return Convert.ToHexString(RandomNumberGenerator.GetBytes(32));
    }
}

public sealed class StressGeneratorOptionException(string message) : Exception(message);
